[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
target_version = ["py36", "py37", "py38", "py39", "py310"]
exclude = "third_party"

[tool.pytest.ini_options]
testpaths = ["python"]
